language: node_js

node_js:
  - "10"

addons:
  chrome: stable
  apt:
    packages:
      # cypress dep
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

before_install:
  - npm install -g @lhci/cli@0.3.x

install:
  - npm ci

script:
  - npm run lint
  - npm run test
  - npm run build
  - lhci autorun
  - npm run e2e:ci
