name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}/chrisottodev
          username: chrisotto6
          password: ${{ secrets.AUTH }}
          registry: docker.pkg.github.com
