name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY	}}
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID	}}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME	}}
      ALGOLIA_SEARCH_ONLY_API_KEY: ${{ secrets.ALGOLIA_SEARCH_ONLY_API_KEY	}}
      FB_APP_ID: ${{ secrets.FB_APP_ID	}}
      GATSBY_DISQUS_NAME: ${{ secrets.GATSBY_DISQUS_NAME	}}
      GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID}}

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install And Lint
        run: yarn install
        run: npm run lint
      - name: Build And Test
        run: npm run build:local
        run: npm test
        run: npm run e2e
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: chrisotto6
          password: ${{ secrets.AUTH }}
          registry: docker.pkg.github.com
        env:
          CI: true
